{% set version = "2.7.5" %}

package:
  name: python-dateutil
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-{{ version }}.tar.gz
  sha256: 88f9287c0174266bb0d8cedd395cfba9c58e87e5ad86b2ce58859bc11be3cf02

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - six

test:
  imports:
    - dateutil
    - dateutil.rrule

about:
  home: https://dateutil.readthedocs.org/
  license: BSD 3 Clause
  license_file: LICENSE
  summary: 'Extensions to the standard Python datetime module.'
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  dev_url: https://github.com/dateutil/dateutil/

extra:
  recipe-maintainers:
    - pganssle
    - msarahan
    - ocefpaf
