{% set name = "python-dateutil" %}
{% set version = "2.9.0.post0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-dateutil-{{ version }}.tar.gz
  sha256: 37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
    - setuptools
  run:
    - python >={{ python_min }}
    - six >=1.5

test:
  imports:
    - dateutil
    - dateutil.parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dateutil.readthedocs.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module.
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  dev_url: https://github.com/dateutil/dateutil/

extra:
  recipe-maintainers:
    - pganssle
    - msarahan
    - ocefpaf
    - thewchan
