# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.9.0.post0

package:
  name: python-dateutil
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-dateutil/python-dateutil-${{ version }}.tar.gz
  sha256: 37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3

build:
  number: 2
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - six >=1.5

tests:
  - python:
      imports:
        - dateutil
        - dateutil.parser
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      file: run_test.py

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module.
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  homepage: https://dateutil.readthedocs.org/
  repository: https://github.com/dateutil/dateutil/
  documentation: https://dateutil.readthedocs.org/en/latest/

extra:
  recipe-maintainers:
    - pganssle
    - msarahan
    - ocefpaf
    - thewchan
